### ISSUE TITLE
Incorrect git repo in README

### ISSUE THREAD

**Issue by crown523** [amosbastian/PMTC-python#4]
Hey,
Was trying to install the program, and noticed that in your README.md it says to clone https://github.com/amosbastian/PMTC.git. However, this is the web app version, so I believe it should say https://github.com/amosbastian/PMTC-python.git instead. Also, instead of cd PMTC/pmtc it would be PMTC-python/pmtc

**Comment by amosbastian** [comment]
Hi @crown523 and thanks! I updated the README, however I don't think this will actually work anymore since it's a long time ago that I made this.
